"""Install the creator/generator toolchains.

"Creators" are the offline generators that turn raw source material into a
browsable library:

* **Comics** - `build_new_comic_collections` and `build_recent_comic_collections`
  unpack CBZ/CBR archives into per-issue web galleries, and
  `build_collection_hub` builds the index page across them. Also included are
  the magazine importers that promote a scanned run into a collection.
* **Books** - the magazine/ebook hub generator that indexes a directory of
  per-collection galleries into one Book Vault landing page.
* **Games** - the per-platform `build_library` scripts that read a ROM directory,
  deduplicate and rank the best dump of each title, extract playable payloads
  and emit the catalog the emulator page consumes. `build_bundle` produces
  js-dos bundles for DOS titles, and `build_world_paths` regenerates the map
  data used by the strategy-game module.

All of them are read-mostly: they read a source directory and write into a
separate generated directory. None of them modifies or deletes source material.
Every generator is exposed through one `cinevault-create` command so an operator
never has to know the individual script names or their environment variables.
"""

from __future__ import annotations

from ..core.fsops import ensure_dir, write_file
from .base import Step, StepResult

#: creator id -> (title, source subdirectory, what it needs)
CREATOR_TOOLCHAINS = {
    "comics": (
        "Comic creators",
        "comics",
        "Reads CBZ/CBR archives from the comics root and writes browsable "
        "galleries into the comic library root.",
    ),
    "books": (
        "Book and magazine creators",
        "books",
        "Indexes per-collection galleries under the books root into one hub page.",
    ),
    "games": (
        "Game library creators",
        "games",
        "Builds each emulator platform's catalog from its ROM directory.",
    ),
}

WRAPPER = """#!/usr/bin/env bash
# CineMediaVault creator dispatcher. Generated by the installer.
#
# Runs a generator as the CineMediaVault service user with the library paths
# already exported, so no generator needs to be edited for this machine.
set -euo pipefail

CONFIG_ENV="{env_file}"
CREATORS="{creators_dir}"
SERVICE_USER="{service_user}"

usage() {{
  cat <<'USAGE'
Usage: cinevault-create <toolchain> <generator> [arguments...]
       cinevault-create list

Toolchains and generators:
  comics  new            rebuild every comic collection gallery
  comics  recent         rebuild only recently added comic collections
  comics  hub            rebuild the comic collection index page
  comics  import-magazine  import a magazine run from CBR archives
  comics  promote-magazine promote an imported run into a collection
  books   hub            rebuild the book/magazine collection hub
  games   build <platform>  rebuild one emulator catalog (nes|sega|dos|mame)
  games   bundle <path>     build a js-dos bundle from a DOS game archive
  games   world-paths       regenerate strategy-game map data

Every generator reads its source library and writes only into the generated
output directory. None of them modifies or deletes source material.
USAGE
}}

if [[ $# -lt 1 ]]; then usage; exit 2; fi

if [[ -r "$CONFIG_ENV" ]]; then
  set -a
  # shellcheck disable=SC1090
  . "$CONFIG_ENV"
  set +a
fi

run_as_service() {{
  if [[ "$(id -un)" == "$SERVICE_USER" ]]; then
    exec "$@"
  fi
  exec setpriv --reuid "$SERVICE_USER" --regid "$SERVICE_USER" --init-groups -- "$@"
}}

toolchain="$1"; shift

case "$toolchain" in
  list) usage; exit 0 ;;
  comics)
    action="${{1:-}}"; shift || true
    case "$action" in
      new)              run_as_service python3 "$CREATORS/comics/build_new_comic_collections.py" "$@" ;;
      recent)           run_as_service python3 "$CREATORS/comics/build_recent_comic_collections.py" "$@" ;;
      hub)              run_as_service python3 "$CREATORS/comics/build_collection_hub.py" "$@" ;;
      import-magazine)  run_as_service python3 "$CREATORS/comics/import_mad_magazine_cbrs.py" "$@" ;;
      promote-magazine) run_as_service python3 "$CREATORS/comics/promote_mad_magazine_collection.py" "$@" ;;
      *) echo "unknown comics generator: ${{action:-<none>}}" >&2; usage; exit 2 ;;
    esac ;;
  books)
    action="${{1:-}}"; shift || true
    case "$action" in
      hub) run_as_service python3 "$CREATORS/books/build_magazine_hub.py" "$@" ;;
      *) echo "unknown books generator: ${{action:-<none>}}" >&2; usage; exit 2 ;;
    esac ;;
  games)
    action="${{1:-}}"; shift || true
    case "$action" in
      build)
        platform="${{1:-}}"; shift || true
        script="$CREATORS/games/$platform/build_library.py"
        if [[ -z "$platform" || ! -f "$script" ]]; then
          echo "unknown or unavailable platform: ${{platform:-<none>}}" >&2; exit 2
        fi
        run_as_service python3 "$script" "$@" ;;
      bundle)      run_as_service python3 "$CREATORS/games/dos/build_bundle.py" "$@" ;;
      world-paths) run_as_service python3 "$CREATORS/games/build_world_paths.py" "$@" ;;
      *) echo "unknown games generator: ${{action:-<none>}}" >&2; usage; exit 2 ;;
    esac ;;
  *) echo "unknown toolchain: $toolchain" >&2; usage; exit 2 ;;
esac
"""


class InstallCreators(Step):
    id = "creators"
    title = "Creator toolchains"
    description = ("Install the comic, book and game generators and the "
                   "cinevault-create dispatcher.")
    depends_on = ("modules.creators", "media.comics_root",
                  "media.comic_library_root", "media.books_root",
                  "media.games_root")
    requires = ("payload", "config")

    def applies(self, ctx) -> bool:
        return bool(ctx.selected_creators())

    def preview(self, ctx) -> str:
        selected = ctx.selected_creators()
        titles = [CREATOR_TOOLCHAINS[c][0] for c in selected if c in CREATOR_TOOLCHAINS]
        return "Install " + ", ".join(titles) + " and the cinevault-create command."

    def run(self, ctx) -> StepResult:
        selected = ctx.selected_creators()
        warnings: list[str] = []

        # Output directories the generators write into. Source libraries are
        # never created here: a missing source is an operator error, not
        # something to paper over with an empty directory.
        if "comics" in selected:
            output = ctx.get("media.comic_library_root")
            if output:
                ensure_dir(output, mode=0o755, user=ctx.service_user,
                           group=ctx.service_group, dry_run=ctx.dry_run,
                           logger=ctx.logger)
                ensure_dir(f"{output}/collections", mode=0o755, user=ctx.service_user,
                           group=ctx.service_group, dry_run=ctx.dry_run,
                           logger=ctx.logger)
            if not ctx.runner.has("unrar") and not ctx.runner.has("unrar-free") \
                    and not ctx.dry_run:
                warnings.append(
                    "No RAR extractor is available, so .cbr archives will be "
                    "skipped by the comic generators. Install unrar-free or the "
                    "non-free unrar package.")

        wrapper = WRAPPER.format(
            env_file=ctx.layout.env_file,
            creators_dir=ctx.layout.creators_dir,
            service_user=ctx.service_user,
        )
        changed = write_file(
            ctx.layout.bin_dir / "cinevault-create", wrapper,
            mode=0o755, user="root", group=ctx.service_group,
            backups=ctx.backups, dry_run=ctx.dry_run, logger=ctx.logger)

        link_changed = self._link(ctx, "cinevault-create")

        result = StepResult(
            changed=changed or link_changed,
            summary=f"{len(selected)} creator toolchain(s) available via "
                    f"`cinevault-create`",
            data={"creators": selected},
        )
        for message in warnings:
            result.warn(message)
        return result

    def _link(self, ctx, name: str) -> bool:
        """Expose a command on PATH, without writing into /usr/bin.

        A missing link is an inconvenience, not a failure: the command still
        works by its full path, so this never aborts an installation.
        """
        import os

        link_dir = ctx.layout.command_link_dir
        if link_dir is None:
            ctx.logger.debug(
                f"relocated install: {name} is available at "
                f"{ctx.layout.bin_dir / name} but is not linked system-wide")
            return False

        link = link_dir / name
        target = ctx.layout.bin_dir / name
        if ctx.dry_run:
            ctx.logger.info(f"[dry-run] would link {link} -> {target}")
            return True
        try:
            link.parent.mkdir(parents=True, exist_ok=True)
            if link.is_symlink() and os.readlink(link) == str(target):
                return False
            if link.exists() or link.is_symlink():
                link.unlink()
            link.symlink_to(target)
        except OSError as exc:
            ctx.logger.warning(
                f"could not link {link}: {exc}. Run {target} by its full path.")
            return False
        ctx.logger.debug(f"linked {link} -> {target}")
        return True


def steps():
    return [InstallCreators()]
