#!/usr/bin/env python3
"""Generate docs/CONFIGURATION-REFERENCE.md from the schema.

The reference is generated rather than written by hand so it cannot drift from
the code that actually validates the configuration. Re-run this after changing
the schema; the test suite checks that the committed file is current.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from installer.config.schema import MEDIA_PATH, PATH, SCHEMA, SECRET  # noqa: E402
from installer.version import CONFIG_SCHEMA_VERSION, INSTALLER_VERSION  # noqa: E402

STAGE_NAMES = {
    0: "derived",
    1: "Welcome", 2: "Administrator", 3: "Network and HTTPS",
    4: "Media locations", 5: "Network shares", 6: "Metadata providers",
    7: "Live TV", 8: "Guide", 9: "Recording", 10: "Subtitles",
    11: "Integrations", 12: "Modules and sizing",
}

SECTION_INTRO = {
    "meta": "Identity of this installation.",
    "deployment": "Overall shape of the install.",
    "admin": "The super-administrator account. Credentials here are consumed "
             "once and never written back to this file.",
    "network": "How clients reach the server, and who is allowed to.",
    "media": "Where your libraries live. These paths are read; CineMediaVault "
             "never moves, renames or deletes source media.",
    "metadata": "Artwork and descriptions from external providers.",
    "livetv": "HDHomeRun tuner and channel selection.",
    "epg": "Programme guide, including the optional private collector.",
    "dvr": "Scheduled recording.",
    "subtitles": "Subtitle discovery and the optional generators.",
    "integrations": "Notifications and links to other systems.",
    "modules": "Which parts of CineMediaVault to install.",
    "transcode": "On-demand conversion, and the bulk library re-encoder.",
    "resources": "How much of the machine CineMediaVault may use.",
    "ops": "Logging, backups and self-healing.",
    "paths": "Where the installer puts things. Change only if you have a "
             "reason to; every other document assumes the defaults.",
}


def render_default(field) -> str:
    if SECRET in field.tags:
        return "_(secret; empty)_"
    value = field.default
    if value is None:
        return "_(none)_"
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    if isinstance(value, list):
        return "`[]`" if not value else "`" + ", ".join(str(v) for v in value) + "`"
    if value == "":
        return '`""`'
    return f"`{value}`"


def render_constraints(field) -> str:
    parts = []
    if field.choices:
        parts.append("one of " + ", ".join(f"`{c}`" for c in field.choices))
    if field.minimum is not None or field.maximum is not None:
        lo = field.minimum if field.minimum is not None else "-"
        hi = field.maximum if field.maximum is not None else "-"
        parts.append(f"range {lo} to {hi}")
    if MEDIA_PATH in field.tags:
        parts.append("absolute path, at least two levels deep, not a system directory")
    elif PATH in field.tags:
        parts.append("absolute path")
    if SECRET in field.tags:
        parts.append("**secret** - stored in `secrets.env` (mode 0640), never in this file")
    return "; ".join(parts) or "-"


def main() -> int:
    lines: list[str] = [
        "# CineMediaVault configuration reference",
        "",
        f"Generated from the schema in `installer/config/schema.py` at installer "
        f"version {INSTALLER_VERSION} (configuration schema v{CONFIG_SCHEMA_VERSION}).",
        "Do not edit this file by hand; run `tools/gen-config-reference.py` instead.",
        "",
        "## How configuration is loaded",
        "",
        "Settings are resolved in this order, later winning over earlier:",
        "",
        "1. the defaults in this document,",
        "2. `/etc/cinemediavault/cinemediavault.yaml`,",
        "3. environment overrides named `CMV_<SECTION>_<KEY>`, for example",
        "   `CMV_NETWORK_HTTPS_PORT=5443`.",
        "",
        "An environment name that matches no setting is an error rather than being",
        "ignored, so a typo is reported instead of silently doing nothing.",
        "",
        "Every value is validated by the same code whichever route it arrives by,",
        "so the browser wizard and an unattended file cannot disagree.",
        "",
        "## Secrets",
        "",
        "Values marked **secret** never appear in `cinemediavault.yaml`. The",
        "installer moves them to `/etc/cinemediavault/secrets.env`, mode 0640,",
        "owned `root:cinevault`. You may put real values in a configuration file",
        "for an unattended install; the installer moves them out and blanks them",
        "on the first write.",
        "",
        "The administrator password is never stored at all. It is converted to a",
        "PBKDF2-SHA256 hash and the plaintext is discarded immediately.",
        "",
    ]

    sections: dict[str, list] = {}
    for field in SCHEMA:
        section = field.key.split(".", 1)[0]
        sections.setdefault(section, []).append(field)

    lines.append("## Settings")
    lines.append("")
    for section, fields in sections.items():
        lines.append(f"### `{section}`")
        lines.append("")
        if section in SECTION_INTRO:
            lines.append(SECTION_INTRO[section])
            lines.append("")
        lines.append("| Setting | Type | Default | Constraints |")
        lines.append("|---|---|---|---|")
        for field in fields:
            leaf = field.key.split(".", 1)[1]
            lines.append(
                f"| `{leaf}` | {field.type} | {render_default(field)} | "
                f"{render_constraints(field)} |")
        lines.append("")
        for field in fields:
            if not field.help:
                continue
            leaf = field.key.split(".", 1)[1]
            stage = STAGE_NAMES.get(field.stage, "")
            suffix = f" _(wizard step: {stage})_" if stage and stage != "derived" else ""
            lines.append(f"**`{field.key}`**{suffix}")
            lines.append("")
            lines.append(field.help)
            lines.append("")

    lines.extend([
        "## Complete example",
        "",
        "Generate a fully commented example with every setting at its default:",
        "",
        "```bash",
        "cinevaultctl config example > my-cinemediavault.yaml",
        "```",
        "",
        "Check it without changing anything:",
        "",
        "```bash",
        "cinevaultctl --config my-cinemediavault.yaml validate",
        "sudo ./install.sh --dry-run --config my-cinemediavault.yaml",
        "```",
        "",
    ])

    target = ROOT / "docs" / "CONFIGURATION-REFERENCE.md"
    target.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {target} ({len(lines)} lines, {len(SCHEMA)} settings)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
