# WebEx notification settings.
webex.enabled=true
webex.token.file=~/.config/webex/token
webex.to.email=jonathan.nicolas@gmail.com
webex.messages.url=https://webexapis.com/v1/messages
webex.status.seconds=3600
