"""Declarative configuration schema for CineMediaVault.

Every setting the wizard collects and every setting an unattended
``cinemediavault.yaml`` may contain is declared here exactly once. The schema
drives four things at the same time:

* validation (types, ranges, enums, cross-field rules),
* the generated documentation in ``docs/CONFIGURATION-REFERENCE.md``,
* the redacted example configuration, and
* which values are treated as secrets and therefore never logged.

Keeping one source of truth is what makes the wizard and the unattended file
provably equivalent: both go through :func:`validate` before anything is
written to disk.
"""

from __future__ import annotations

import ipaddress
import re
import shlex
from dataclasses import dataclass, field
from typing import Any, Callable, Iterable, Sequence

# --------------------------------------------------------------------------
# Field definition
# --------------------------------------------------------------------------

SECRET = "secret"
PATH = "path"
MEDIA_PATH = "media_path"


@dataclass(frozen=True)
class Field:
    """One configuration key."""

    key: str                       # dotted path, e.g. "network.https_port"
    type: str                      # str|int|float|bool|list|dict|enum
    default: Any = None
    required: bool = False
    choices: Sequence[Any] | None = None
    minimum: float | None = None
    maximum: float | None = None
    pattern: str | None = None
    tags: frozenset[str] = frozenset()
    help: str = ""
    stage: int = 0                 # wizard stage that collects it (0 = derived)

    @property
    def is_secret(self) -> bool:
        return SECRET in self.tags

    @property
    def is_path(self) -> bool:
        return PATH in self.tags or MEDIA_PATH in self.tags


def _f(key, type_, **kw) -> Field:
    tags = kw.pop("tags", ())
    return Field(key=key, type=type_, tags=frozenset(tags), **kw)


# --------------------------------------------------------------------------
# The schema
# --------------------------------------------------------------------------

TIMEZONE_RE = r"^[A-Za-z]+(?:/[A-Za-z0-9_+\-]+){0,2}$"
HOSTNAME_RE = r"^[a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?)*$"
USERNAME_RE = r"^[a-z_][a-z0-9_-]{0,31}$"

SCHEMA: tuple[Field, ...] = (
    # ---- meta -----------------------------------------------------------
    _f("meta.schema_version", "int", default=1,
       help="Configuration schema version. Managed by the installer; do not edit."),
    _f("meta.installer_version", "str", default="",
       help="Installer version that last wrote this file."),
    _f("meta.instance_name", "str", default="CineMediaVault", stage=1,
       pattern=r"^[\w .\-]{1,64}$",
       help="Friendly name shown in the CineMediaVault interface."),

    # ---- stage 1: deployment mode --------------------------------------
    _f("deployment.mode", "enum", default="standard", stage=1,
       choices=("standard", "minimal", "everything"),
       help="standard = media libraries + Live TV/DVR. minimal = core web app and "
            "movies/TV only. everything = every optional module the hardware supports."),
    _f("deployment.accept_licenses", "bool", default=False, stage=1,
       help="Confirms the operator accepts the third-party licences listed in "
            "docs/THIRD-PARTY-NOTICES.md before optional components are downloaded."),
    _f("deployment.timezone", "str", default="UTC", stage=1, pattern=TIMEZONE_RE,
       help="IANA timezone used for schedules, the EPG grid and DVR padding."),

    # ---- stage 2: administrator ----------------------------------------
    _f("admin.username", "str", required=True, stage=2, pattern=USERNAME_RE,
       help="CineMediaVault super-administrator login name."),
    _f("admin.full_name", "str", default="", stage=2, pattern=r"^[^\x00-\x1f]{0,128}$",
       help="Display name for the administrator account."),
    _f("admin.email", "str", default="", stage=2,
       pattern=r"^$|^[^@\s]+@[^@\s]+\.[^@\s]+$",
       help="Optional contact address for the administrator account."),
    # Not marked `required`: the cross-field rule below owns this, because an
    # already-installed configuration legitimately has neither the password nor
    # the hash - the account lives in the database by then.
    _f("admin.password", "str", stage=2, tags=(SECRET,),
       help="Administrator password. Never written to the configuration file, never "
            "logged; converted to a PBKDF2-SHA256 hash and discarded immediately. "
            "Required only when creating the account for the first time."),
    _f("admin.password_hash", "str", default="", stage=0, tags=(SECRET,),
       help="Derived PBKDF2-SHA256 hash. Generated by the installer."),

    # ---- stage 3: network / TLS ----------------------------------------
    _f("network.hostname", "str", default="cinemediavault.local", stage=3,
       pattern=HOSTNAME_RE,
       help="Hostname clients use to reach this server. Used for TLS names and "
            "for the URLs shown on the Modules page."),
    _f("network.listen_address", "str", default="0.0.0.0", stage=3,
       help="Address CineMediaVault binds. 0.0.0.0 = all interfaces."),
    _f("network.http_port", "int", default=8080, stage=3, minimum=1, maximum=65535,
       help="Plain HTTP port. Set enable_http to false to disable it."),
    _f("network.enable_http", "bool", default=False, stage=3,
       help="Serve plain HTTP in addition to HTTPS. Off by default."),
    _f("network.https_port", "int", default=5000, stage=3, minimum=1, maximum=65535,
       help="HTTPS port. This is the primary CineMediaVault port."),
    _f("network.tls_mode", "enum", default="self_signed", stage=3,
       choices=("self_signed", "provided", "acme_dns", "none"),
       help="self_signed = installer generates a local certificate. provided = you "
            "supply cert/key paths. acme_dns = use an existing certbot DNS-01 "
            "deployment. none = HTTP only (not recommended)."),
    _f("network.tls_cert_path", "str", default="", stage=3, tags=(PATH,),
       help="Certificate chain (PEM) when tls_mode is 'provided'."),
    _f("network.tls_key_path", "str", default="", stage=3, tags=(PATH,),
       help="Private key (PEM) when tls_mode is 'provided'. Never copied into backups."),
    _f("network.trusted_networks", "list", default=["192.168.0.0/16", "10.0.0.0/8",
                                                    "172.16.0.0/12", "127.0.0.0/8"],
       stage=3,
       help="CIDR ranges allowed to reach the setup wizard and the EPG collector. "
            "Public ranges are rejected."),
    _f("network.configure_firewall", "bool", default=True, stage=3,
       help="Add ufw rules for the ports this install actually uses."),

    # ---- stage 4/5: media locations ------------------------------------
    _f("media.movies_root", "str", default="", stage=4, tags=(MEDIA_PATH,),
       help="Movie library root. Empty disables the Movies module."),
    _f("media.tv_root", "str", default="", stage=4, tags=(MEDIA_PATH,),
       help="TV library root. Empty disables the TV module."),
    _f("media.music_root", "str", default="", stage=4, tags=(MEDIA_PATH,),
       help="Music library root. Empty disables the Music module."),
    _f("media.books_root", "str", default="", stage=4, tags=(MEDIA_PATH,),
       help="Ebook/audiobook root for Book Vault."),
    _f("media.comics_root", "str", default="", stage=4, tags=(MEDIA_PATH,),
       help="Source comics (CBZ/CBR) root."),
    _f("media.comic_library_root", "str", default="", stage=4, tags=(MEDIA_PATH,),
       help="Generated browsable comic library. Written to by the comic creators."),
    _f("media.games_root", "str", default="", stage=4, tags=(MEDIA_PATH,),
       help="ROM/game root. Sub-directories per platform."),
    _f("media.recordings_root", "str", default="", stage=4, tags=(MEDIA_PATH,),
       help="DVR recording destination. Must be writable and on a sized volume."),
    _f("media.create_missing", "bool", default=False, stage=4,
       help="Create media directories that do not exist yet. Never touches existing "
            "content; refuses paths that are not empty and not already a library."),

    _f("media.mounts", "list", default=[], stage=5,
       help="Network mounts the installer should validate (and optionally add to "
            "/etc/fstab). Each entry: {type: nfs|cifs, source, mountpoint, "
            "options, credentials_file, manage_fstab}."),

    # ---- stage 6: metadata providers -----------------------------------
    _f("metadata.tmdb_api_key", "str", default="", stage=6, tags=(SECRET,),
       help="TMDb v3 API key for movie/TV metadata and posters."),
    _f("metadata.tmdb_read_access_token", "str", default="", stage=6, tags=(SECRET,),
       help="TMDb v4 read access token. Either this or the API key is enough."),
    _f("metadata.google_books_api_key", "str", default="", stage=6, tags=(SECRET,),
       help="Optional Google Books key used by Book Vault for richer book metadata."),
    _f("metadata.refresh_cron", "str", default="*/15 * * * *", stage=6,
       help="How often the catalogue index is refreshed (systemd OnCalendar is "
            "derived from this)."),
    _f("metadata.fetch_on_install", "bool", default=False, stage=6,
       help="Run a first metadata/poster fetch during installation. Off by default "
            "because a large library can take hours and hit provider rate limits."),

    # ---- stage 7: Live TV / HDHomeRun ----------------------------------
    _f("livetv.enabled", "bool", default=False, stage=7,
       help="Enable Live TV, the guide grid and the DVR."),
    _f("livetv.discovery", "enum", default="auto", stage=7,
       choices=("auto", "manual", "none"),
       help="auto = query the HDHomeRun discovery service on the LAN. manual = use "
            "the address below."),
    _f("livetv.device_address", "str", default="", stage=7,
       help="HDHomeRun IP address when discovery is manual."),
    _f("livetv.device_id", "str", default="", stage=7, pattern=r"^$|^[0-9A-Fa-f]{8}$",
       help="HDHomeRun device ID, recorded so a replaced tuner is noticed."),
    _f("livetv.tuner_count", "int", default=0, stage=7, minimum=0, maximum=16,
       help="Number of tuners. The DVR refuses to exceed this. 0 = read from device."),
    _f("livetv.reserved_tuners", "int", default=0, stage=7, minimum=0, maximum=16,
       help="Tuners the DVR will never claim, so live viewing always has one free."),
    _f("livetv.channels", "list", default=[], stage=7,
       help="Selected channel numbers. Empty = every channel the device reports."),

    # ---- stage 8: EPG ---------------------------------------------------
    _f("epg.mode", "enum", default="device_only", stage=8,
       choices=("device_only", "extended"),
       help="device_only = the tuner's own ~2-day guide. extended = additionally run "
            "the private iptv-org/epg collector on this CineVault host and append "
            "about 12 more days into one unified guide."),
    _f("epg.collector_bind_address", "str", default="127.0.0.1", stage=8,
       help="Address the EPG collector container binds. Never 0.0.0.0."),
    _f("epg.collector_port", "int", default=3010, stage=8, minimum=1, maximum=65535,
       help="Host port for the collector's read-only XMLTV feed."),
    _f("epg.feed_url", "str", default="", stage=8,
       help="XMLTV URL CineMediaVault merges from. Derived from the collector "
            "settings unless you point at an existing feed."),
    _f("epg.horizon_days", "int", default=14, stage=8, minimum=1, maximum=14,
       help="Combined guide horizon. With the tuner's authoritative ~2 days, 14 "
            "produces approximately 12 appended days. Fourteen is the verified ceiling."),
    _f("epg.local_cache_max_age_hours", "int", default=12, stage=8,
       minimum=1, maximum=48,
       help="Maximum age of the tuner's local guide cache before CineVault refreshes it."),
    _f("epg.refresh_time", "str", default="03:20", stage=8,
       pattern=r"^([01]\d|2[0-3]):[0-5]\d$",
       help="Local time of the daily collection run."),
    _f("epg.request_delay_ms", "int", default=2500, stage=8, minimum=500, maximum=30000,
       help="Pause between upstream requests. Lower values risk being blocked."),
    _f("epg.max_connections", "int", default=1, stage=8, minimum=1, maximum=4,
       help="Concurrent upstream requests. Keep at 1 to stay polite."),
    _f("epg.request_timeout_ms", "int", default=45000, stage=8,
       minimum=5000, maximum=180000, help="Per-request timeout for the collector."),
    _f("epg.memory_limit_mb", "int", default=3072, stage=8, minimum=1024, maximum=16384,
       help="Container memory ceiling. The grabber holds a full guide in memory."),
    _f("epg.cpu_limit", "float", default=1.5, stage=8, minimum=0.25, maximum=16.0,
       help="Container CPU ceiling."),
    _f("epg.channel_map", "str", default="", stage=8, tags=(PATH,),
       help="Optional verified channels.xml mapping tuner channels to upstream site "
            "IDs. Without it the collector has nothing to grab and extension stays off."),

    # ---- stage 9: DVR ---------------------------------------------------
    _f("dvr.enabled", "bool", default=False, stage=9,
       help="Enable scheduled recording."),
    _f("dvr.padding_start_seconds", "int", default=60, stage=9, minimum=0, maximum=3600,
       help="Seconds to start early."),
    _f("dvr.padding_end_seconds", "int", default=120, stage=9, minimum=0, maximum=7200,
       help="Seconds to keep recording after the scheduled end."),
    _f("dvr.retention_days", "int", default=0, stage=9, minimum=0, maximum=3650,
       help="Automatic deletion age. 0 disables automatic deletion (the default)."),
    _f("dvr.conflict_policy", "enum", default="priority", stage=9,
       choices=("priority", "first_scheduled", "manual"),
       help="How the scheduler resolves more recordings than tuners."),
    _f("dvr.min_free_gb", "int", default=20, stage=9, minimum=1, maximum=10000,
       help="Recording is refused when the destination drops below this."),
    _f("dvr.poll_seconds", "int", default=5, stage=9, minimum=2, maximum=120,
       help="Scheduler tick interval."),

    # ---- stage 10: subtitles -------------------------------------------
    _f("subtitles.use_existing", "bool", default=True, stage=10,
       help="Serve sidecar .srt files and embedded text subtitle streams."),
    _f("subtitles.languages", "list", default=["en"], stage=10,
       help="Language codes to discover and, when generation is on, to produce."),
    _f("subtitles.subdl_enabled", "bool", default=False, stage=10,
       help="Look up missing subtitles on SubDL before falling back to Whisper."),
    _f("subtitles.subdl_api_key", "str", default="", stage=10, tags=(SECRET,),
       help="SubDL API key. Stored in the root-only secret file."),
    _f("subtitles.subdl_daily_search_limit", "int", default=2000, stage=10,
       minimum=1, maximum=100000,
       help="Daily search cap, matching the documented free-tier limit."),
    _f("subtitles.whisper_enabled", "bool", default=False, stage=10,
       help="Install the local Whisper transcription pipeline. Heavyweight: pulls a "
            "private Python environment and multi-gigabyte models."),
    _f("subtitles.whisper_model", "enum", default="small", stage=10,
       choices=("tiny", "base", "small", "medium", "large-v3"),
       help="Model size. large-v3 effectively needs a CUDA GPU."),
    _f("subtitles.whisper_device", "enum", default="auto", stage=10,
       choices=("auto", "cpu", "cuda"),
       help="Compute device for transcription."),
    _f("subtitles.whisper_workers", "int", default=1, stage=10, minimum=1, maximum=4,
       help="Concurrent transcription workers. More than 1 needs isolated scratch."),
    _f("subtitles.whisper_cpu_quota_percent", "int", default=200, stage=10,
       minimum=25, maximum=1600,
       help="systemd CPUQuota for the worker. 200 = two cores."),
    _f("subtitles.whisper_memory_limit_mb", "int", default=6144, stage=10,
       minimum=1024, maximum=65536, help="systemd MemoryMax for the worker."),
    _f("subtitles.whisper_start_enabled", "bool", default=False, stage=10,
       help="Start the worker immediately after installation. Off by default so the "
            "first catalogue pass is a deliberate decision."),

    # ---- stage 11: integrations / notifications ------------------------
    _f("integrations.webex_webhook_url", "str", default="", stage=11, tags=(SECRET,),
       help="Optional Webex incoming-webhook URL for DVR and health notifications."),
    _f("integrations.homepage_enabled", "bool", default=False, stage=11,
       help="Expose the counts/status JSON that Homepage dashboards consume."),
    _f("integrations.transcode_control_url", "str", default="", stage=11,
       help="Optional existing Transcode Control instance to link from Modules."),
    _f("integrations.transcode_control_db", "str", default="", stage=11, tags=(PATH,),
       help="Path to a Transcode Control SQLite database. Required only for the "
            "Whisper start/stop bridge on the Modules page."),
    _f("integrations.notify_on_install", "bool", default=False, stage=11,
       help="Send one notification when installation finishes."),

    # ---- stage 12: modules ----------------------------------------------
    _f("modules.movies", "bool", default=True, stage=12, help="Movies library."),
    _f("modules.tv", "bool", default=True, stage=12, help="TV library."),
    _f("modules.music", "bool", default=False, stage=12, help="Music library and player."),
    _f("modules.bookvault", "bool", default=False, stage=12, help="Book Vault (ebooks/audiobooks)."),
    _f("modules.comics", "bool", default=False, stage=12, help="Comics library."),
    _f("modules.video_wall", "bool", default=True, stage=12, help="Four-tile Video Wall."),
    _f("modules.downloads", "bool", default=True, stage=12,
       help="Browser and Android companion downloads, including compressed mobile copies."),
    _f("modules.games", "list", default=[], stage=12,
       help="Emulator modules to install: nes, sega, dos, mame, gameboy, gba, n64, "
            "ps1, c64, atari2600, atari5200, atari7800, arcade."),
    _f("modules.creators", "list", default=[], stage=12,
       help="Creator/generator toolchains to install: comics, books, games."),
    _f("modules.bookvault_port", "int", default=8112, stage=12,
       minimum=1, maximum=65535, help="Port the Book Vault server listens on."),
    _f("modules.comics_port", "int", default=8110, stage=12,
       minimum=1, maximum=65535, help="Port the comics library listens on."),
    _f("modules.game_port_base", "int", default=8090, stage=12, minimum=1024, maximum=65000,
       help="First port for emulator modules; each one takes the next free port."),

    # ---- transcoding -----------------------------------------------------
    _f("transcode.hls_enabled", "bool", default=True, stage=12,
       help="Allow on-the-fly HLS for clients that cannot direct-play."),
    _f("transcode.hls_encoder", "enum", default="auto", stage=12,
       choices=("auto", "cpu", "nvenc", "vaapi", "qsv"),
       help="Hardware encoder preference for HLS."),
    _f("transcode.hls_video_bitrate", "str", default="4500k", stage=12,
       pattern=r"^\d+[kKmM]$",
       help="Target bitrate for on-the-fly conversion. 4500k suits 1080p; "
            "lower it if clients buffer over a slow link."),
    _f("transcode.hls_cache_max_age_hours", "float", default=6.0, stage=12,
       minimum=0.5, maximum=168.0,
       help="How long converted segments are kept before the cache is swept."),
    _f("transcode.default_playback_mode", "enum", default="direct", stage=12,
       choices=("direct", "hls"),
       help="direct plays the original file whenever the client can, which "
            "costs no CPU. hls converts everything."),
    _f("transcode.library_queue_enabled", "bool", default=False, stage=12,
       help="Install the bulk library transcode queue. Always installed STOPPED and "
            "with an empty queue: it rewrites source media and must be armed "
            "deliberately."),
    _f("transcode.library_queue_autostart", "bool", default=False, stage=12,
       help="Refused unless library_queue_enabled is true AND the operator has "
            "explicitly accepted that it modifies source media."),
    _f("transcode.mobile_download_target_mb_per_hour", "int", default=150, stage=12,
       minimum=20, maximum=4000,
       help="Size budget for compressed downloads to phones, per hour of "
            "video. The server refuses a result that overshoots this or that "
            "grows larger than the source."),

    # ---- resources / sizing ---------------------------------------------
    _f("resources.app_memory_limit_mb", "int", default=2048, stage=12,
       minimum=512, maximum=131072, help="systemd MemoryMax for the main service."),
    _f("resources.app_cpu_quota_percent", "int", default=0, stage=12,
       minimum=0, maximum=6400,
       help="systemd CPUQuota for the main service. 0 = unlimited."),
    _f("resources.scan_worker_threads", "int", default=4, stage=12, minimum=1, maximum=64,
       help="Threads used by library scans and thumbnail generation."),

    # ---- promo/barker channel (optional, heavyweight) --------------------
    # Genre discovery and the ten-movie/ten-TV virtual channel guide
    # (genre_catalog.py, virtual_channels.py) are always-on core application
    # modules - like Movies or TV - with no installer switch, matching the live
    # 2026-09-08 application exactly. Only this spoken-preview add-on is optional.
    # Off by default, same reasoning as Whisper: a private venv, a ~350 MB
    # model pair the operator must supply, and an ffmpeg render pass on a timer.
    _f("promo_channel.enabled", "bool", default=False, stage=12,
       help="Generate a spoken-narration promo reel (Kokoro TTS + ffmpeg) previewing "
            "upcoming virtual-channel programming on a timer. Requires vchannels.enabled "
            "and the two Kokoro model files supplied by the operator (see "
            "docs/PROMO-BARKER-CHANNEL.md); nothing is downloaded automatically."),
    _f("promo_channel.model_path", "str", default="", stage=12, tags=(PATH,),
       help="Path to the operator-supplied kokoro-v1.0.onnx weights file. Required "
            "when promo_channel.enabled is true."),
    _f("promo_channel.voices_path", "str", default="", stage=12, tags=(PATH,),
       help="Path to the operator-supplied voices-v1.0.bin voice pack. Required "
            "when promo_channel.enabled is true."),
    _f("promo_channel.schedule_calendar", "str", default="*-*-* 05,11,17,23:05:00",
       stage=12,
       help="systemd OnCalendar expression for reel generation. Default: four "
            "times a day, one hour before each 6-hour broadcast boundary."),
    _f("promo_channel.minutes", "int", default=60, stage=12, minimum=10, maximum=180,
       help="Length of each generated reel."),
    _f("promo_channel.cpu_quota_percent", "int", default=150, stage=12,
       minimum=25, maximum=800, help="systemd CPUQuota for the render timer."),
    _f("promo_channel.memory_limit_mb", "int", default=4096, stage=12,
       minimum=1024, maximum=32768, help="systemd MemoryMax for the render timer."),

    # ---- operations ------------------------------------------------------
    _f("ops.log_level", "enum", default="info",
       choices=("debug", "info", "warning", "error"),
       help="How much detail the installer and services write to their logs."),
    _f("ops.log_retain_days", "int", default=14, minimum=1, maximum=365,
       help="Days of rotated logs to keep before they are deleted."),
    _f("ops.db_backup_time", "str", default="01:00",
       pattern=r"^([01]\d|2[0-3]):[0-5]\d$",
       help="Local time of the nightly database backup. Keep it clear of the "
            "EPG collection window so the two do not compete for disk."),
    _f("ops.db_backup_keep", "int", default=10, minimum=1, maximum=365,
       help="Number of database backups to retain. Older ones are pruned "
            "automatically; at least one is always kept."),
    _f("ops.health_check_enabled", "bool", default=True,
       help="Run a health probe every minute and restart the service if it "
            "stops answering."),
    _f("ops.health_failure_threshold", "int", default=2, minimum=1, maximum=10,
       help="Consecutive failed probes before a restart. Do not set this to 1: "
            "a single stalled probe on a busy server is normal, and restarting "
            "on it would interrupt playback and mask real failures."),
    _f("ops.health_restart_cooldown_seconds", "int", default=300,
       minimum=30, maximum=86400,
       help="Minimum seconds between two health-triggered restarts. Stops a "
            "restart storm when the service dies again immediately."),
    _f("ops.session_days", "int", default=30, minimum=1, maximum=365,
       help="How long a signed-in browser session stays valid."),
    _f("ops.poster_rotation_seconds", "int", default=21600,
       minimum=60, maximum=604800,
       help="How often the home and sign-in background artwork changes. The "
            "selection is cached so a restart does not rotate it early."),

    # ---- install layout (advanced) ---------------------------------------
    _f("paths.install_root", "str", default="/opt/cinemediavault", tags=(PATH,),
       help="Where the application itself is installed. Root-owned and never "
            "writable by the service."),
    _f("paths.config_root", "str", default="/etc/cinemediavault", tags=(PATH,),
       help="Configuration and secrets."),
    _f("paths.state_root", "str", default="/var/lib/cinemediavault", tags=(PATH,),
       help="Databases, generated metadata, artwork and backups."),
    _f("paths.log_root", "str", default="/var/log/cinemediavault", tags=(PATH,),
       help="Log files."),
    _f("paths.cache_root", "str", default="/var/cache/cinemediavault", tags=(PATH,),
       help="Regenerable caches: HLS segments, subtitles, mobile downloads. "
            "Safe to delete when the service is stopped."),
    _f("paths.service_user", "str", default="cinevault", pattern=USERNAME_RE,
       help="Unprivileged system account the services run as."),
    _f("paths.service_group", "str", default="cinevault", pattern=USERNAME_RE,
       help="Group that may read the secret files."),
)

SCHEMA_BY_KEY: dict[str, Field] = {f.key: f for f in SCHEMA}
SECRET_KEYS: tuple[str, ...] = tuple(f.key for f in SCHEMA if f.is_secret)


# --------------------------------------------------------------------------
# Path safety
# --------------------------------------------------------------------------

#: Directories that must never be handed to a scanner, a creator or the DVR.
#: A library root here would make a recursive scan walk the whole system, and a
#: "create missing" or cleanup action catastrophic.
FORBIDDEN_MEDIA_PATHS = frozenset({
    "/", "/bin", "/boot", "/dev", "/etc", "/lib", "/lib32", "/lib64", "/libx32",
    "/proc", "/root", "/run", "/sbin", "/sys", "/usr", "/var",
    "/usr/bin", "/usr/sbin", "/usr/lib", "/usr/local", "/usr/share",
    "/var/lib", "/var/log", "/var/run", "/var/cache", "/var/tmp",
    "/home", "/opt", "/srv", "/mnt", "/media", "/tmp", "/snap",
})

#: A media path must be at least this many components deep. "/mnt" is refused,
#: "/mnt/media" is accepted. This is the single rule that stops an operator from
#: pointing the scanner at an entire mount tree by accident.
MIN_MEDIA_PATH_DEPTH = 2


class PathSafetyError(ValueError):
    """Raised when a path would be dangerous to use as a media or state root."""


def check_media_path(value: str, *, label: str = "path") -> str:
    """Validate a media/library path. Returns the normalised path.

    Refuses relative paths, traversal, symlink-escaping roots, system
    directories, and anything too shallow to be a real library.
    """
    import os

    if not value or not value.strip():
        raise PathSafetyError(f"{label} is empty")
    raw = value.strip()
    if not raw.startswith("/"):
        raise PathSafetyError(f"{label} must be an absolute path, got {raw!r}")
    if "\x00" in raw:
        raise PathSafetyError(f"{label} contains a null byte")
    if ".." in raw.split("/"):
        raise PathSafetyError(f"{label} must not contain '..': {raw!r}")

    norm = os.path.normpath(raw).rstrip("/") or "/"
    if norm in FORBIDDEN_MEDIA_PATHS:
        raise PathSafetyError(
            f"{label} {norm!r} is a system directory. Choose a dedicated media "
            f"directory such as {norm.rstrip('/')}/CineMediaVault instead."
        )
    depth = len([p for p in norm.split("/") if p])
    if depth < MIN_MEDIA_PATH_DEPTH:
        raise PathSafetyError(
            f"{label} {norm!r} is too broad (depth {depth}). A library root must be "
            f"at least {MIN_MEDIA_PATH_DEPTH} levels deep, for example "
            f"{norm}/CineMediaVault."
        )
    return norm


def check_system_path(value: str, *, label: str = "path") -> str:
    """Validate an installer-owned path (install/state/log roots, cert files)."""
    import os

    if not value or not value.strip():
        raise PathSafetyError(f"{label} is empty")
    raw = value.strip()
    if not raw.startswith("/"):
        raise PathSafetyError(f"{label} must be an absolute path, got {raw!r}")
    if ".." in raw.split("/"):
        raise PathSafetyError(f"{label} must not contain '..': {raw!r}")
    norm = os.path.normpath(raw).rstrip("/") or "/"
    if norm == "/":
        raise PathSafetyError(f"{label} must not be '/'")
    return norm


# --------------------------------------------------------------------------
# Network safety
# --------------------------------------------------------------------------

#: The ranges a home network can legitimately live in. Membership is checked
#: against these explicitly rather than trusting ``ip_network.is_private``:
#: Python classifies ``0.0.0.0/0`` - the whole internet - as private, because
#: ``0.0.0.0/8`` is a reserved "this network" block. Accepting that would open
#: the firewall to the world and let the EPG collector bind every interface,
#: which is precisely what this installer promises never to do.
PRIVATE_RANGES = tuple(ipaddress.ip_network(r) for r in (
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16",
    "127.0.0.0/8",
    "169.254.0.0/16",
    "100.64.0.0/10",        # CGNAT, used by Tailscale and similar overlays
    "fc00::/7",             # unique local
    "fe80::/10",            # link local
    "::1/128",
))


def is_private_cidr(cidr: str) -> bool:
    """True when *cidr* lies entirely inside a real private range."""
    try:
        net = ipaddress.ip_network(cidr, strict=False)
    except ValueError:
        return False
    if net.network_address.is_unspecified:
        return False
    return any(net.subnet_of(candidate) for candidate in PRIVATE_RANGES
               if candidate.version == net.version)


def is_private_address(addr: str) -> bool:
    """True when *addr* is a specific private address.

    ``0.0.0.0`` and ``::`` are rejected: they are wildcards meaning "every
    interface", not private addresses, and binding them is the opposite of
    keeping a service off the public internet.
    """
    try:
        ip = ipaddress.ip_address(addr)
    except ValueError:
        return False
    if ip.is_unspecified:
        return False
    return any(ip in candidate for candidate in PRIVATE_RANGES
               if candidate.version == ip.version)


# --------------------------------------------------------------------------
# Validation
# --------------------------------------------------------------------------

@dataclass
class Issue:
    key: str
    message: str
    severity: str = "error"        # error | warning

    def __str__(self) -> str:
        return f"[{self.severity}] {self.key}: {self.message}"


def get(config: dict, key: str, default: Any = None) -> Any:
    node: Any = config
    for part in key.split("."):
        if not isinstance(node, dict) or part not in node:
            return default
        node = node[part]
    return node


def put(config: dict, key: str, value: Any) -> None:
    parts = key.split(".")
    node = config
    for part in parts[:-1]:
        nxt = node.get(part)
        if not isinstance(nxt, dict):
            nxt = {}
            node[part] = nxt
        node = nxt
    node[parts[-1]] = value


def apply_defaults(config: dict) -> dict:
    """Return *config* with every unset schema key filled from its default."""
    import copy
    out = copy.deepcopy(config) if config else {}
    for f in SCHEMA:
        if get(out, f.key, _MISSING) is _MISSING:
            default = f.default
            if isinstance(default, (list, dict)):
                default = copy.deepcopy(default)
            put(out, f.key, default)
    return out


class _Missing:
    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return "<missing>"


_MISSING = _Missing()

_TYPE_MAP = {
    "str": str,
    "int": int,
    "float": (int, float),
    "bool": bool,
    "list": list,
    "dict": dict,
}

KNOWN_GAMES = ("nes", "sega", "dos", "mame", "gameboy", "gba", "n64", "ps1",
               "c64", "atari2600", "atari5200", "atari7800", "arcade")
KNOWN_CREATORS = ("comics", "books", "games")
KNOWN_MOUNT_TYPES = ("nfs", "cifs")


def validate(config: dict, *, for_install: bool = True) -> list[Issue]:
    """Validate a fully-defaulted configuration.

    ``for_install=False`` relaxes rules that only matter at install time (for
    example a partially-filled wizard draft), so the same function can validate
    each wizard stage as it is entered.
    """
    issues: list[Issue] = []
    cfg = apply_defaults(config)

    for f in SCHEMA:
        value = get(cfg, f.key, _MISSING)
        if value is _MISSING or value is None:
            if f.required and for_install:
                issues.append(Issue(f.key, "is required"))
            continue

        # type
        if f.type == "enum":
            if f.choices and value not in f.choices:
                issues.append(Issue(f.key, f"must be one of {list(f.choices)}, got {value!r}"))
            continue
        expected = _TYPE_MAP.get(f.type)
        if expected and not isinstance(value, expected):
            # bool is a subclass of int; guard against silent acceptance
            if not (f.type in ("int", "float") and isinstance(value, bool) is False
                    and isinstance(value, (int, float))):
                issues.append(Issue(f.key, f"must be {f.type}, got {type(value).__name__}"))
                continue
        if f.type in ("int", "float") and isinstance(value, bool):
            issues.append(Issue(f.key, f"must be {f.type}, got bool"))
            continue

        # range
        if f.minimum is not None and isinstance(value, (int, float)) and value < f.minimum:
            issues.append(Issue(f.key, f"must be >= {f.minimum}, got {value}"))
        if f.maximum is not None and isinstance(value, (int, float)) and value > f.maximum:
            issues.append(Issue(f.key, f"must be <= {f.maximum}, got {value}"))

        # pattern
        if f.pattern and isinstance(value, str) and not re.match(f.pattern, value):
            issues.append(Issue(f.key, "has an invalid format"))

        # paths
        if MEDIA_PATH in f.tags and isinstance(value, str) and value.strip():
            try:
                check_media_path(value, label=f.key)
            except PathSafetyError as exc:
                issues.append(Issue(f.key, str(exc)))
        elif PATH in f.tags and isinstance(value, str) and value.strip():
            try:
                check_system_path(value, label=f.key)
            except PathSafetyError as exc:
                issues.append(Issue(f.key, str(exc)))

    issues.extend(_cross_field_rules(cfg, for_install=for_install))
    return issues


def _cross_field_rules(cfg: dict, *, for_install: bool) -> list[Issue]:
    issues: list[Issue] = []
    g = lambda k, d=None: get(cfg, k, d)  # noqa: E731

    # --- password strength (only when a plaintext password is present) ----
    password = g("admin.password") or ""
    if password:
        issues.extend(check_password(password))
    elif for_install and not g("admin.password_hash"):
        issues.append(Issue("admin.password", "is required"))

    # --- ports must be unique and free of well-known conflicts -----------
    ports: dict[int, str] = {}

    def claim(port: Any, owner: str) -> None:
        if not isinstance(port, int) or port <= 0:
            return
        if port in ports:
            issues.append(Issue(owner, f"port {port} is already used by {ports[port]}"))
        else:
            ports[port] = owner

    if g("network.enable_http"):
        claim(g("network.http_port"), "network.http_port")
    if g("network.tls_mode") != "none":
        claim(g("network.https_port"), "network.https_port")
    if g("modules.bookvault"):
        claim(g("modules.bookvault_port"), "modules.bookvault_port")
    if g("modules.comics"):
        claim(g("modules.comics_port"), "modules.comics_port")
    if g("epg.mode") == "extended":
        claim(g("epg.collector_port"), "epg.collector_port")
    base = g("modules.game_port_base") or 8090
    for offset, game in enumerate(g("modules.games") or []):
        claim(base + offset, f"modules.games[{game}]")

    # --- TLS -------------------------------------------------------------
    tls_mode = g("network.tls_mode")
    if tls_mode == "provided":
        for key in ("network.tls_cert_path", "network.tls_key_path"):
            if not (g(key) or "").strip():
                issues.append(Issue(key, "is required when tls_mode is 'provided'"))
    if tls_mode == "none" and not g("network.enable_http"):
        issues.append(Issue("network.tls_mode",
                            "'none' requires network.enable_http to be true, otherwise "
                            "nothing would be listening"))

    # --- trusted networks must stay private ------------------------------
    for cidr in g("network.trusted_networks") or []:
        if not isinstance(cidr, str) or not is_private_cidr(cidr):
            issues.append(Issue("network.trusted_networks",
                                f"{cidr!r} is not a private/loopback range. The setup "
                                f"wizard and EPG collector are never exposed publicly."))

    # --- listen address ---------------------------------------------------
    listen = g("network.listen_address") or ""
    if listen not in ("0.0.0.0", "::"):
        if listen and not _valid_ip(listen):
            issues.append(Issue("network.listen_address", f"{listen!r} is not a valid IP address"))

    # --- module <-> media coupling ---------------------------------------
    pairs = (
        ("modules.movies", "media.movies_root", "Movies"),
        ("modules.tv", "media.tv_root", "TV"),
        ("modules.music", "media.music_root", "Music"),
        ("modules.bookvault", "media.books_root", "Book Vault"),
        ("modules.comics", "media.comics_root", "Comics"),
    )
    for module_key, path_key, label in pairs:
        if g(module_key) and not (g(path_key) or "").strip():
            issues.append(Issue(path_key, f"{label} is enabled but no library path is set"))

    if (g("modules.games") or []) and not (g("media.games_root") or "").strip():
        issues.append(Issue("media.games_root",
                            "game modules are selected but no games root is set"))
    for game in g("modules.games") or []:
        if game not in KNOWN_GAMES:
            issues.append(Issue("modules.games", f"unknown game module {game!r}"))
    for creator in g("modules.creators") or []:
        if creator not in KNOWN_CREATORS:
            issues.append(Issue("modules.creators", f"unknown creator toolchain {creator!r}"))
    if "comics" in (g("modules.creators") or []) and not (g("media.comic_library_root") or "").strip():
        issues.append(Issue("media.comic_library_root",
                            "the comic creators need an output library path"))

    # --- media roots must not overlap or nest -----------------------------
    roots: list[tuple[str, str]] = []
    for f in SCHEMA:
        if MEDIA_PATH in f.tags:
            v = (g(f.key) or "").strip()
            if v:
                roots.append((f.key, v.rstrip("/")))
    for i, (k1, p1) in enumerate(roots):
        for k2, p2 in roots[i + 1:]:
            if p1 == p2:
                if not _overlap_allowed(k1, k2):
                    issues.append(Issue(k2, f"is the same path as {k1} ({p1})",
                                        severity="warning"))
            elif p1.startswith(p2 + "/") or p2.startswith(p1 + "/"):
                issues.append(Issue(k2, f"is nested with {k1} ({p1} / {p2}). Nested "
                                        f"libraries cause double-scanning.",
                                    severity="warning"))

    # --- Live TV / DVR / EPG ---------------------------------------------
    if g("dvr.enabled"):
        if not g("livetv.enabled"):
            issues.append(Issue("dvr.enabled", "requires livetv.enabled"))
        if not (g("media.recordings_root") or "").strip():
            issues.append(Issue("media.recordings_root", "is required when the DVR is enabled"))
        tuners = g("livetv.tuner_count") or 0
        reserved = g("livetv.reserved_tuners") or 0
        if tuners and reserved >= tuners:
            issues.append(Issue("livetv.reserved_tuners",
                                f"reserves all {tuners} tuners, leaving none for recording"))
    if g("livetv.enabled") and g("livetv.discovery") == "manual":
        addr = (g("livetv.device_address") or "").strip()
        if not addr:
            issues.append(Issue("livetv.device_address", "is required for manual discovery"))
        elif not _valid_ip(addr):
            issues.append(Issue("livetv.device_address", f"{addr!r} is not a valid IP address"))

    if g("epg.mode") == "extended":
        if not g("livetv.enabled"):
            issues.append(Issue("epg.mode", "extended guide requires Live TV"))
        if not is_private_address(g("epg.collector_bind_address") or ""):
            issues.append(Issue("epg.collector_bind_address",
                                "must be a private or loopback address; the collector "
                                "is never published to the internet"))
        if not (g("epg.channel_map") or "").strip():
            issues.append(Issue("epg.channel_map",
                                "extended EPG needs a verified channels.xml. Without one "
                                "the collector has nothing to grab.",
                                severity="warning"))
        if (g("epg.request_delay_ms") or 0) < 1000:
            issues.append(Issue("epg.request_delay_ms",
                                "below 1000 ms is likely to get the collector blocked",
                                severity="warning"))

    # --- subtitles ---------------------------------------------------------
    if g("subtitles.subdl_enabled") and not (g("subtitles.subdl_api_key") or "").strip():
        issues.append(Issue("subtitles.subdl_api_key", "is required when SubDL is enabled"))
    if g("subtitles.whisper_enabled"):
        if not g("subtitles.languages"):
            issues.append(Issue("subtitles.languages", "at least one language is required"))
        if g("subtitles.whisper_model") in ("medium", "large-v3") and \
                g("subtitles.whisper_device") == "cpu":
            issues.append(Issue("subtitles.whisper_model",
                                "medium/large-v3 on CPU can take many hours per title",
                                severity="warning"))
    if g("subtitles.whisper_start_enabled") and not g("subtitles.whisper_enabled"):
        issues.append(Issue("subtitles.whisper_start_enabled",
                            "cannot start a pipeline that is not installed"))

    # --- promo/barker channel ------------------------------------------------
    if g("promo_channel.enabled"):
        if not (g("promo_channel.model_path") or "").strip():
            issues.append(Issue("promo_channel.model_path",
                                "is required when promo_channel.enabled is true "
                                "(the Kokoro ONNX weights are not downloaded "
                                "automatically - see docs/PROMO-BARKER-CHANNEL.md)"))
        if not (g("promo_channel.voices_path") or "").strip():
            issues.append(Issue("promo_channel.voices_path",
                                "is required when promo_channel.enabled is true "
                                "(the Kokoro voice pack is not downloaded "
                                "automatically - see docs/PROMO-BARKER-CHANNEL.md)"))

    # --- transcoding safety -------------------------------------------------
    if g("transcode.library_queue_autostart") and not g("transcode.library_queue_enabled"):
        issues.append(Issue("transcode.library_queue_autostart",
                            "requires transcode.library_queue_enabled"))

    # --- licences -----------------------------------------------------------
    needs_licence = bool(g("modules.games")) or g("epg.mode") == "extended" or \
        g("subtitles.whisper_enabled")
    if for_install and needs_licence and not g("deployment.accept_licenses"):
        issues.append(Issue("deployment.accept_licenses",
                            "must be true: the selected components download "
                            "third-party software with its own licences "
                            "(see docs/THIRD-PARTY-NOTICES.md)"))

    # --- mounts -------------------------------------------------------------
    for index, mount in enumerate(g("media.mounts") or []):
        label = f"media.mounts[{index}]"
        if not isinstance(mount, dict):
            issues.append(Issue(label, "must be a mapping"))
            continue
        if mount.get("type") not in KNOWN_MOUNT_TYPES:
            issues.append(Issue(label, f"type must be one of {list(KNOWN_MOUNT_TYPES)}"))
        for required in ("source", "mountpoint"):
            if not str(mount.get(required) or "").strip():
                issues.append(Issue(label, f"{required} is required"))
        mp = str(mount.get("mountpoint") or "").strip()
        if mp:
            try:
                check_media_path(mp, label=f"{label}.mountpoint")
            except PathSafetyError as exc:
                issues.append(Issue(label, str(exc)))
        opts = str(mount.get("options") or "")
        if opts and not re.match(r"^[A-Za-z0-9_,=./:@\-+]*$", opts):
            issues.append(Issue(label, "options contain characters that are not "
                                       "valid in an fstab option list"))
        creds = str(mount.get("credentials_file") or "").strip()
        if mount.get("type") == "cifs" and creds:
            try:
                check_system_path(creds, label=f"{label}.credentials_file")
            except PathSafetyError as exc:
                issues.append(Issue(label, str(exc)))

    return issues


def _overlap_allowed(k1: str, k2: str) -> bool:
    # Comics source and generated comic library legitimately share a parent but
    # not the same directory; nothing else may collide.
    return False


def _valid_ip(value: str) -> bool:
    try:
        ipaddress.ip_address(value)
        return True
    except ValueError:
        return False


# --------------------------------------------------------------------------
# Password policy
# --------------------------------------------------------------------------

MIN_PASSWORD_LENGTH = 12

COMMON_PASSWORDS = frozenset({
    "password", "password1", "password123", "12345678", "123456789", "1234567890",
    "qwertyuiop", "letmein", "welcome", "admin", "admin123", "administrator",
    "changeme", "cinevault", "cinemediavault", "iloveyou", "monkey", "dragon",
    "baseball", "football", "sunshine", "princess", "passw0rd", "trustno1",
    "admin1", "qwerty123", "1q2w3e4r5t", "abc12345",
})


def check_password(password: str) -> list[Issue]:
    """Password rules. The password itself is never included in a message."""
    issues: list[Issue] = []
    if len(password) < MIN_PASSWORD_LENGTH:
        issues.append(Issue("admin.password",
                            f"must be at least {MIN_PASSWORD_LENGTH} characters"))
    if password.lower() in COMMON_PASSWORDS:
        issues.append(Issue("admin.password", "is a commonly used password"))
    classes = sum((
        bool(re.search(r"[a-z]", password)),
        bool(re.search(r"[A-Z]", password)),
        bool(re.search(r"\d", password)),
        bool(re.search(r"[^\w\s]", password)),
    ))
    if classes < 3:
        issues.append(Issue("admin.password",
                            "must mix at least three of: lowercase, uppercase, "
                            "digits, symbols"))
    if "\x00" in password or "\n" in password or "\r" in password:
        issues.append(Issue("admin.password", "must not contain control characters"))
    if len(password) > 256:
        issues.append(Issue("admin.password", "must be 256 characters or fewer"))
    return issues


def errors(issues: Iterable[Issue]) -> list[Issue]:
    return [i for i in issues if i.severity == "error"]


def warnings(issues: Iterable[Issue]) -> list[Issue]:
    return [i for i in issues if i.severity == "warning"]
