"""Secret storage.

Secrets never appear in ``cinemediavault.yaml``. They live in a single
``secrets.env`` written with mode 0640, owned ``root:<service-group>``, so the
CineMediaVault service can read it through ``EnvironmentFile=`` while ordinary
accounts cannot. The admin password is never stored at all: only its
PBKDF2-SHA256 hash, in a separate root-only bootstrap file that the application
consumes once.
"""

from __future__ import annotations

import base64
import hashlib
import json
import os
import re
import secrets as _secrets
from pathlib import Path

from ..core.fsops import write_file
from ..core.redact import REDACTOR
from .schema import SECRET_KEYS, get

#: Environment variable each secret is exported as. These names are the ones
#: the CineMediaVault application already reads.
SECRET_ENV_MAP: dict[str, str] = {
    "metadata.tmdb_api_key": "TMDB_API_KEY",
    "metadata.tmdb_read_access_token": "TMDB_READ_ACCESS_TOKEN",
    "metadata.google_books_api_key": "GOOGLE_BOOKS_API_KEY",
    "subtitles.subdl_api_key": "SUBDL_API_KEY",
    "integrations.webex_webhook_url": "CINEVAULT_WEBEX_WEBHOOK_URL",
}

#: Iterations for the administrator password hash. Matches the application's
#: own ``password_hash`` so the produced hash verifies without any change there.
PBKDF2_ROUNDS = 260000

ENV_NAME_RE = re.compile(r"^[A-Z][A-Z0-9_]*$")


def hash_password(password: str, *, salt: bytes | None = None,
                  rounds: int = PBKDF2_ROUNDS) -> str:
    """Produce the exact hash format CineMediaVault verifies.

    ``pbkdf2_sha256$<rounds>$<b64 salt>$<b64 digest>``
    """
    if not isinstance(password, str) or not password:
        raise ValueError("password must be a non-empty string")
    salt = salt or _secrets.token_bytes(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, rounds)
    return (f"pbkdf2_sha256${rounds}$"
            f"{base64.b64encode(salt).decode()}${base64.b64encode(digest).decode()}")


def verify_password(password: str, stored: str) -> bool:
    """Mirror of the application's verifier; used by tests and the smoke test."""
    import hmac
    try:
        scheme, rounds, salt_b64, digest_b64 = stored.split("$", 3)
        if scheme != "pbkdf2_sha256":
            return False
        salt = base64.b64decode(salt_b64.encode())
        expected = base64.b64decode(digest_b64.encode())
        actual = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, int(rounds))
        return hmac.compare_digest(actual, expected)
    except (ValueError, TypeError):
        return False


def generate_token(length: int = 32) -> str:
    """URL-safe random token for the wizard bootstrap and session cookies."""
    return _secrets.token_urlsafe(length)


def env_quote(value: str) -> str:
    """Quote a value for a systemd ``EnvironmentFile``.

    systemd's parser accepts double-quoted strings with backslash escapes. A
    value is always quoted so that spaces, ``#`` and ``$`` are literal.
    """
    escaped = (str(value)
               .replace("\\", "\\\\")
               .replace('"', '\\"')
               .replace("\n", "\\n")
               .replace("\r", ""))
    return f'"{escaped}"'


def render_env_file(pairs: dict[str, str], *, header: str = "") -> str:
    lines: list[str] = []
    if header:
        for line in header.strip().splitlines():
            lines.append(f"# {line}" if line.strip() else "#")
        lines.append("")
    for name in sorted(pairs):
        if not ENV_NAME_RE.match(name):
            raise ValueError(f"invalid environment variable name: {name!r}")
        value = pairs[name]
        if value is None:
            continue
        lines.append(f"{name}={env_quote(value)}")
    return "\n".join(lines) + "\n"


class SecretStore:
    """Reads and writes the secret environment file."""

    HEADER = (
        "CineMediaVault secrets.\n"
        "Generated by the installer. Mode 0640, root:<service group>.\n"
        "Never commit this file, never include it in a source backup, and never\n"
        "paste its contents into a support request or an AI handoff."
    )

    def __init__(self, path: str | os.PathLike, *, group: str | None = None):
        self.path = Path(path)
        self.group = group

    # -- read ---------------------------------------------------------------
    def read(self) -> dict[str, str]:
        if not self.path.is_file():
            return {}
        values: dict[str, str] = {}
        for line in self.path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            name, _, raw = line.partition("=")
            raw = raw.strip()
            if len(raw) >= 2 and raw[0] == raw[-1] == '"':
                raw = (raw[1:-1]
                       .replace("\\n", "\n")
                       .replace('\\"', '"')
                       .replace("\\\\", "\\"))
            values[name.strip()] = raw
        return values

    # -- write --------------------------------------------------------------
    def write(self, config: dict, *, extra: dict[str, str] | None = None,
              backups=None, dry_run: bool = False) -> bool:
        """Write every configured secret. Missing values are omitted, not blanked."""
        pairs: dict[str, str] = {}
        for key, env_name in SECRET_ENV_MAP.items():
            value = get(config, key)
            if value not in (None, ""):
                pairs[env_name] = str(value)
        for name, value in (extra or {}).items():
            if value not in (None, ""):
                pairs[name] = str(value)
        REDACTOR.register_many(pairs.values())
        return write_file(
            self.path,
            render_env_file(pairs, header=self.HEADER),
            mode=0o640,
            user="root" if os.geteuid() == 0 else None,
            group=self.group if os.geteuid() == 0 else None,
            backups=backups,
            dry_run=dry_run,
        )


class AdminBootstrap:
    """The one-shot administrator bootstrap file.

    The application creates its super-administrator from this file on first
    start and the installer removes the plaintext password from memory as soon
    as the hash exists. The file itself holds only the hash, is mode 0640, and
    is deleted by ``cinevaultctl`` once the account is confirmed present.
    """

    def __init__(self, path: str | os.PathLike, *, group: str | None = None):
        self.path = Path(path)
        self.group = group

    def write(self, *, username: str, password_hash: str, full_name: str = "",
              email: str = "", backups=None, dry_run: bool = False) -> bool:
        if not password_hash.startswith("pbkdf2_sha256$"):
            raise ValueError("refusing to write a bootstrap file without a PBKDF2 hash")
        payload = {
            "username": username,
            "full_name": full_name,
            "email": email,
            "password_hash": password_hash,
        }
        REDACTOR.register(password_hash)
        return write_file(
            self.path,
            json.dumps(payload, indent=2) + "\n",
            mode=0o640,
            user="root" if os.geteuid() == 0 else None,
            group=self.group if os.geteuid() == 0 else None,
            backups=backups,
            dry_run=dry_run,
        )

    def exists(self) -> bool:
        return self.path.is_file()

    def remove(self) -> bool:
        try:
            self.path.unlink()
            return True
        except FileNotFoundError:
            return False


def scrub(config: dict) -> dict:
    """Return a copy of *config* with plaintext secrets removed.

    Called immediately after hashing so no later code path - logging, the
    journal, a crash traceback - can see the administrator password.
    """
    import copy
    out = copy.deepcopy(config)
    from .schema import put
    put(out, "admin.password", "")
    for key in SECRET_KEYS:
        if key == "admin.password_hash":
            continue
        if key == "admin.password":
            continue
    return out
